### ISSUE TITLE
Mail versenden immer mit Contao Mailer

### ISSUE THREAD

**Issue by hac121170** [friends-of-contao/contao-memberlist#10]
Hallo,

wenn wir über die Erweiterung eine Mail versenden, dann erscheint immer als Absendername "from Contao Mailer". Kann man dieses ändern?

**Comment by cliffparnitzky** [comment]
Das müsste man hier konfigurierbar machen: https://github.com/friends-of-contao/contao-memberlist/blob/master/system/modules/memberlist/modules/ModuleMemberlist.php#L369

**Comment by fritzmg** [comment]
Fixed in 85a3947
