### ISSUE TITLE
compatibility to PHP 7 

### ISSUE THREAD

**Issue by ChrMue** [friends-of-contao/contao-memberlist#11]
To ensure the compatibility to PHP 7 it would be necessary to use the class StringUtil instead of String if the contao release >= 3.5 is used.
The file ModuleMemberlist.php had to be modified near line 70
`	protected function compile()
	{
		if (!version_compare(VERSION, '3.5', '<'))
		{
			$this->import('StringUtil');
		}
		else 
		{	
			$this->import('String');
		}
`
BR
ChrMue

.

**Comment by cliffparnitzky** [comment]
Closed with 34ea46f24d5bdc1329ae49df032c313a5a1ca8fe
