### ISSUE TITLE
Deutsche Übersetzung in Contao 4.8 fehlt gänzlich

### ISSUE THREAD

**Issue by Nightwing0815** [friends-of-contao/contao-memberlist#17]
Hi!
Mit Version 4.8 von Contao fehlt die deutsche Übersetzung gänzlich, nur zur Info ;-)

ToM

**Comment by fritzmg** [comment]
What exactly do you mean?

**Comment by Nightwing0815** [comment]
Sorry for late response, had to think about...
I attach a screenshot, that'll say more:
![foc](https://user-images.githubusercontent.com/54181775/86737605-b4a89180-c034-11ea-977a-883459839b0c.PNG)
Just installed it on my 4.10-dev installation right now, to create the pic.

ToM

**Comment by fritzmg** [comment]
Please describe what your screenshot actually shows ;).

**Comment by Nightwing0815** [comment]
Oh no, you know the saying: a pic shows more than thousand words? :-)

Okay, the screen shows the memberlist module. Since version 4.8, the localization isn't german any more, only standard (english), as shown. The page is german only, and before it worked well.
Can you verify that?

ToM

**Comment by fritzmg** [comment]
You mean you don't see the labels. But I cannot confirm that actually - even though I should, when looking at the code 😁

**Comment by fritzmg** [comment]
See https://github.com/friends-of-contao/contao-memberlist/pull/21

**Comment by Nightwing0815** [comment]
Thank you...again :-)

ToM
