### ISSUE TITLE
Lizenzschlüssel

### ISSUE THREAD

**Issue by dsdata** [friends-of-contao/contao-memberlist#2]
Guten Tag,
auf der Extension Seite https://contao.org/de/extension-list/view/memberlist.10030009.de.html wird beschrieben das man hier auf der Seite Infos findet "Freigabe Notizen".

Nun... ich konnte diese noch nicht finden, wie lautet der Lizenzschlüssel???

**Comment by cliffparnitzky** [comment]
Support thread. Should be closed.
