### ISSUE TITLE
Freigabe für Contao 3.3

### ISSUE THREAD

**Issue by BugBuster1701** [friends-of-contao/contao-memberlist#6]
Ich nutze die Freigabe der öffentliche Felder im BE für meine Erweiterung (lastlogin), dass funktioniert. Das FE Modul konnte ich auch erfolgreich testen.
Da gibt es aber bestimmt noch mehr zu testen denke ich mal.

**Comment by cliffparnitzky** [comment]
may be closed, is compatible
